name: msp
monitor :  loss
loss :  categorical_crossentropy
optimizer :  adam
classifier_name :  fcn
batch_size : 32
lr : 0.001
reduce_lr_factor : 0.5
reduce_lr_patience : 50
min_lr : 0.0001
epochs: 100