default_random_state: 42
default_n_init: 10
min_clusters: 2
max_clusters: 15
min_silhouette_samples: 2
scale_data_for_clustering: True
reduce_dimensions_for_clustering: False
dimensionality_reduction_method: pca

